//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSistemaLibros.ServiceSistemaLibros {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCFServicioLibreria")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoLibro", Namespace="http://schemas.datacontract.org/2004/07/WCFServicioLibreria")]
    [System.SerializableAttribute()]
    public partial class DtoLibro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dmeDateReservationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string varCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string varStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string varTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dmeDateReservation {
            get {
                return this.dmeDateReservationField;
            }
            set {
                if ((this.dmeDateReservationField.Equals(value) != true)) {
                    this.dmeDateReservationField = value;
                    this.RaisePropertyChanged("dmeDateReservation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idItem {
            get {
                return this.idItemField;
            }
            set {
                if ((this.idItemField.Equals(value) != true)) {
                    this.idItemField = value;
                    this.RaisePropertyChanged("idItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string varCode {
            get {
                return this.varCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.varCodeField, value) != true)) {
                    this.varCodeField = value;
                    this.RaisePropertyChanged("varCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string varStatus {
            get {
                return this.varStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.varStatusField, value) != true)) {
                    this.varStatusField = value;
                    this.RaisePropertyChanged("varStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string varTitle {
            get {
                return this.varTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.varTitleField, value) != true)) {
                    this.varTitleField = value;
                    this.RaisePropertyChanged("varTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reservation", Namespace="http://schemas.datacontract.org/2004/07/WCFServicioLibreria")]
    [System.SerializableAttribute()]
    public partial class Reservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bolIsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dmeDateCreateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dmeDateReservationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dmeDateUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idBookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idReservationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bolIsActive {
            get {
                return this.bolIsActiveField;
            }
            set {
                if ((this.bolIsActiveField.Equals(value) != true)) {
                    this.bolIsActiveField = value;
                    this.RaisePropertyChanged("bolIsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dmeDateCreate {
            get {
                return this.dmeDateCreateField;
            }
            set {
                if ((this.dmeDateCreateField.Equals(value) != true)) {
                    this.dmeDateCreateField = value;
                    this.RaisePropertyChanged("dmeDateCreate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dmeDateReservation {
            get {
                return this.dmeDateReservationField;
            }
            set {
                if ((this.dmeDateReservationField.Equals(value) != true)) {
                    this.dmeDateReservationField = value;
                    this.RaisePropertyChanged("dmeDateReservation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dmeDateUpdate {
            get {
                return this.dmeDateUpdateField;
            }
            set {
                if ((this.dmeDateUpdateField.Equals(value) != true)) {
                    this.dmeDateUpdateField = value;
                    this.RaisePropertyChanged("dmeDateUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idBook {
            get {
                return this.idBookField;
            }
            set {
                if ((this.idBookField.Equals(value) != true)) {
                    this.idBookField = value;
                    this.RaisePropertyChanged("idBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idReservation {
            get {
                return this.idReservationField;
            }
            set {
                if ((this.idReservationField.Equals(value) != true)) {
                    this.idReservationField = value;
                    this.RaisePropertyChanged("idReservation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUser {
            get {
                return this.idUserField;
            }
            set {
                if ((this.idUserField.Equals(value) != true)) {
                    this.idUserField = value;
                    this.RaisePropertyChanged("idUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intStatus {
            get {
                return this.intStatusField;
            }
            set {
                if ((this.intStatusField.Equals(value) != true)) {
                    this.intStatusField = value;
                    this.RaisePropertyChanged("intStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/WCFServicioLibreria")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bolIsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dmeDateCreateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dmeDateUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string varEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string varFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string varLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string varPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bolIsActive {
            get {
                return this.bolIsActiveField;
            }
            set {
                if ((this.bolIsActiveField.Equals(value) != true)) {
                    this.bolIsActiveField = value;
                    this.RaisePropertyChanged("bolIsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dmeDateCreate {
            get {
                return this.dmeDateCreateField;
            }
            set {
                if ((this.dmeDateCreateField.Equals(value) != true)) {
                    this.dmeDateCreateField = value;
                    this.RaisePropertyChanged("dmeDateCreate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dmeDateUpdate {
            get {
                return this.dmeDateUpdateField;
            }
            set {
                if ((this.dmeDateUpdateField.Equals(value) != true)) {
                    this.dmeDateUpdateField = value;
                    this.RaisePropertyChanged("dmeDateUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUser {
            get {
                return this.idUserField;
            }
            set {
                if ((this.idUserField.Equals(value) != true)) {
                    this.idUserField = value;
                    this.RaisePropertyChanged("idUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intStatus {
            get {
                return this.intStatusField;
            }
            set {
                if ((this.intStatusField.Equals(value) != true)) {
                    this.intStatusField = value;
                    this.RaisePropertyChanged("intStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string varEmail {
            get {
                return this.varEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.varEmailField, value) != true)) {
                    this.varEmailField = value;
                    this.RaisePropertyChanged("varEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string varFirstName {
            get {
                return this.varFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.varFirstNameField, value) != true)) {
                    this.varFirstNameField = value;
                    this.RaisePropertyChanged("varFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string varLastName {
            get {
                return this.varLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.varLastNameField, value) != true)) {
                    this.varLastNameField = value;
                    this.RaisePropertyChanged("varLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string varPassword {
            get {
                return this.varPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.varPasswordField, value) != true)) {
                    this.varPasswordField = value;
                    this.RaisePropertyChanged("varPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/WCFServicioLibreria")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bolIsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bolIsReservatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dmeDateCreateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dmeDateUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idBookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string varCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string varTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bolIsActive {
            get {
                return this.bolIsActiveField;
            }
            set {
                if ((this.bolIsActiveField.Equals(value) != true)) {
                    this.bolIsActiveField = value;
                    this.RaisePropertyChanged("bolIsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bolIsReservated {
            get {
                return this.bolIsReservatedField;
            }
            set {
                if ((this.bolIsReservatedField.Equals(value) != true)) {
                    this.bolIsReservatedField = value;
                    this.RaisePropertyChanged("bolIsReservated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dmeDateCreate {
            get {
                return this.dmeDateCreateField;
            }
            set {
                if ((this.dmeDateCreateField.Equals(value) != true)) {
                    this.dmeDateCreateField = value;
                    this.RaisePropertyChanged("dmeDateCreate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dmeDateUpdate {
            get {
                return this.dmeDateUpdateField;
            }
            set {
                if ((this.dmeDateUpdateField.Equals(value) != true)) {
                    this.dmeDateUpdateField = value;
                    this.RaisePropertyChanged("dmeDateUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idBook {
            get {
                return this.idBookField;
            }
            set {
                if ((this.idBookField.Equals(value) != true)) {
                    this.idBookField = value;
                    this.RaisePropertyChanged("idBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intStatus {
            get {
                return this.intStatusField;
            }
            set {
                if ((this.intStatusField.Equals(value) != true)) {
                    this.intStatusField = value;
                    this.RaisePropertyChanged("intStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string varCode {
            get {
                return this.varCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.varCodeField, value) != true)) {
                    this.varCodeField = value;
                    this.RaisePropertyChanged("varCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string varTitle {
            get {
                return this.varTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.varTitleField, value) != true)) {
                    this.varTitleField = value;
                    this.RaisePropertyChanged("varTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MensajeNotificacion", Namespace="http://schemas.datacontract.org/2004/07/WCFServicioLibreria")]
    [System.SerializableAttribute()]
    public partial class MensajeNotificacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string varDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string varDescription {
            get {
                return this.varDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.varDescriptionField, value) != true)) {
                    this.varDescriptionField = value;
                    this.RaisePropertyChanged("varDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSistemaLibros.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        MVCSistemaLibros.ServiceSistemaLibros.CompositeType GetDataUsingDataContract(MVCSistemaLibros.ServiceSistemaLibros.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MVCSistemaLibros.ServiceSistemaLibros.CompositeType> GetDataUsingDataContractAsync(MVCSistemaLibros.ServiceSistemaLibros.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_LISTARVISTALIBROS", ReplyAction="http://tempuri.org/IService1/SP_LISTARVISTALIBROSResponse")]
        MVCSistemaLibros.ServiceSistemaLibros.DtoLibro[] SP_LISTARVISTALIBROS(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_LISTARVISTALIBROS", ReplyAction="http://tempuri.org/IService1/SP_LISTARVISTALIBROSResponse")]
        System.Threading.Tasks.Task<MVCSistemaLibros.ServiceSistemaLibros.DtoLibro[]> SP_LISTARVISTALIBROSAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_RESERVARLIBRO", ReplyAction="http://tempuri.org/IService1/SP_RESERVARLIBROResponse")]
        void SP_RESERVARLIBRO(MVCSistemaLibros.ServiceSistemaLibros.Reservation reservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_RESERVARLIBRO", ReplyAction="http://tempuri.org/IService1/SP_RESERVARLIBROResponse")]
        System.Threading.Tasks.Task SP_RESERVARLIBROAsync(MVCSistemaLibros.ServiceSistemaLibros.Reservation reservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_OBTENERUSUARIOXEMAIL", ReplyAction="http://tempuri.org/IService1/SP_OBTENERUSUARIOXEMAILResponse")]
        MVCSistemaLibros.ServiceSistemaLibros.User SP_OBTENERUSUARIOXEMAIL(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_OBTENERUSUARIOXEMAIL", ReplyAction="http://tempuri.org/IService1/SP_OBTENERUSUARIOXEMAILResponse")]
        System.Threading.Tasks.Task<MVCSistemaLibros.ServiceSistemaLibros.User> SP_OBTENERUSUARIOXEMAILAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_VALIDARRESERVAXLIBRO", ReplyAction="http://tempuri.org/IService1/SP_VALIDARRESERVAXLIBROResponse")]
        int SP_VALIDARRESERVAXLIBRO(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_VALIDARRESERVAXLIBRO", ReplyAction="http://tempuri.org/IService1/SP_VALIDARRESERVAXLIBROResponse")]
        System.Threading.Tasks.Task<int> SP_VALIDARRESERVAXLIBROAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_VALIDARRESERVAXUSUARIOXLIBRO", ReplyAction="http://tempuri.org/IService1/SP_VALIDARRESERVAXUSUARIOXLIBROResponse")]
        int SP_VALIDARRESERVAXUSUARIOXLIBRO(int idUser, string varCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_VALIDARRESERVAXUSUARIOXLIBRO", ReplyAction="http://tempuri.org/IService1/SP_VALIDARRESERVAXUSUARIOXLIBROResponse")]
        System.Threading.Tasks.Task<int> SP_VALIDARRESERVAXUSUARIOXLIBROAsync(int idUser, string varCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_BUSCARLIBROXCODE", ReplyAction="http://tempuri.org/IService1/SP_BUSCARLIBROXCODEResponse")]
        MVCSistemaLibros.ServiceSistemaLibros.Book SP_BUSCARLIBROXCODE(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_BUSCARLIBROXCODE", ReplyAction="http://tempuri.org/IService1/SP_BUSCARLIBROXCODEResponse")]
        System.Threading.Tasks.Task<MVCSistemaLibros.ServiceSistemaLibros.Book> SP_BUSCARLIBROXCODEAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_RESERVARCOLA", ReplyAction="http://tempuri.org/IService1/SP_RESERVARCOLAResponse")]
        void SP_RESERVARCOLA(int idUser, int idBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_RESERVARCOLA", ReplyAction="http://tempuri.org/IService1/SP_RESERVARCOLAResponse")]
        System.Threading.Tasks.Task SP_RESERVARCOLAAsync(int idUser, int idBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_VALIDARCOLA", ReplyAction="http://tempuri.org/IService1/SP_VALIDARCOLAResponse")]
        int SP_VALIDARCOLA(int idUser, int idBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_VALIDARCOLA", ReplyAction="http://tempuri.org/IService1/SP_VALIDARCOLAResponse")]
        System.Threading.Tasks.Task<int> SP_VALIDARCOLAAsync(int idUser, int idBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_LISTARNOTIFICACIONESXUSUARIO", ReplyAction="http://tempuri.org/IService1/SP_LISTARNOTIFICACIONESXUSUARIOResponse")]
        MVCSistemaLibros.ServiceSistemaLibros.MensajeNotificacion[] SP_LISTARNOTIFICACIONESXUSUARIO(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_LISTARNOTIFICACIONESXUSUARIO", ReplyAction="http://tempuri.org/IService1/SP_LISTARNOTIFICACIONESXUSUARIOResponse")]
        System.Threading.Tasks.Task<MVCSistemaLibros.ServiceSistemaLibros.MensajeNotificacion[]> SP_LISTARNOTIFICACIONESXUSUARIOAsync(int idUser);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MVCSistemaLibros.ServiceSistemaLibros.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MVCSistemaLibros.ServiceSistemaLibros.IService1>, MVCSistemaLibros.ServiceSistemaLibros.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public MVCSistemaLibros.ServiceSistemaLibros.CompositeType GetDataUsingDataContract(MVCSistemaLibros.ServiceSistemaLibros.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MVCSistemaLibros.ServiceSistemaLibros.CompositeType> GetDataUsingDataContractAsync(MVCSistemaLibros.ServiceSistemaLibros.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public MVCSistemaLibros.ServiceSistemaLibros.DtoLibro[] SP_LISTARVISTALIBROS(string code) {
            return base.Channel.SP_LISTARVISTALIBROS(code);
        }
        
        public System.Threading.Tasks.Task<MVCSistemaLibros.ServiceSistemaLibros.DtoLibro[]> SP_LISTARVISTALIBROSAsync(string code) {
            return base.Channel.SP_LISTARVISTALIBROSAsync(code);
        }
        
        public void SP_RESERVARLIBRO(MVCSistemaLibros.ServiceSistemaLibros.Reservation reservation) {
            base.Channel.SP_RESERVARLIBRO(reservation);
        }
        
        public System.Threading.Tasks.Task SP_RESERVARLIBROAsync(MVCSistemaLibros.ServiceSistemaLibros.Reservation reservation) {
            return base.Channel.SP_RESERVARLIBROAsync(reservation);
        }
        
        public MVCSistemaLibros.ServiceSistemaLibros.User SP_OBTENERUSUARIOXEMAIL(string email) {
            return base.Channel.SP_OBTENERUSUARIOXEMAIL(email);
        }
        
        public System.Threading.Tasks.Task<MVCSistemaLibros.ServiceSistemaLibros.User> SP_OBTENERUSUARIOXEMAILAsync(string email) {
            return base.Channel.SP_OBTENERUSUARIOXEMAILAsync(email);
        }
        
        public int SP_VALIDARRESERVAXLIBRO(string code) {
            return base.Channel.SP_VALIDARRESERVAXLIBRO(code);
        }
        
        public System.Threading.Tasks.Task<int> SP_VALIDARRESERVAXLIBROAsync(string code) {
            return base.Channel.SP_VALIDARRESERVAXLIBROAsync(code);
        }
        
        public int SP_VALIDARRESERVAXUSUARIOXLIBRO(int idUser, string varCode) {
            return base.Channel.SP_VALIDARRESERVAXUSUARIOXLIBRO(idUser, varCode);
        }
        
        public System.Threading.Tasks.Task<int> SP_VALIDARRESERVAXUSUARIOXLIBROAsync(int idUser, string varCode) {
            return base.Channel.SP_VALIDARRESERVAXUSUARIOXLIBROAsync(idUser, varCode);
        }
        
        public MVCSistemaLibros.ServiceSistemaLibros.Book SP_BUSCARLIBROXCODE(string code) {
            return base.Channel.SP_BUSCARLIBROXCODE(code);
        }
        
        public System.Threading.Tasks.Task<MVCSistemaLibros.ServiceSistemaLibros.Book> SP_BUSCARLIBROXCODEAsync(string code) {
            return base.Channel.SP_BUSCARLIBROXCODEAsync(code);
        }
        
        public void SP_RESERVARCOLA(int idUser, int idBook) {
            base.Channel.SP_RESERVARCOLA(idUser, idBook);
        }
        
        public System.Threading.Tasks.Task SP_RESERVARCOLAAsync(int idUser, int idBook) {
            return base.Channel.SP_RESERVARCOLAAsync(idUser, idBook);
        }
        
        public int SP_VALIDARCOLA(int idUser, int idBook) {
            return base.Channel.SP_VALIDARCOLA(idUser, idBook);
        }
        
        public System.Threading.Tasks.Task<int> SP_VALIDARCOLAAsync(int idUser, int idBook) {
            return base.Channel.SP_VALIDARCOLAAsync(idUser, idBook);
        }
        
        public MVCSistemaLibros.ServiceSistemaLibros.MensajeNotificacion[] SP_LISTARNOTIFICACIONESXUSUARIO(int idUser) {
            return base.Channel.SP_LISTARNOTIFICACIONESXUSUARIO(idUser);
        }
        
        public System.Threading.Tasks.Task<MVCSistemaLibros.ServiceSistemaLibros.MensajeNotificacion[]> SP_LISTARNOTIFICACIONESXUSUARIOAsync(int idUser) {
            return base.Channel.SP_LISTARNOTIFICACIONESXUSUARIOAsync(idUser);
        }
    }
}
